### PR TITLE
Edits to match interface changes

### PR DESCRIPTION
**Pull request by clifford-smith**
Largely edits to match interface changes and increase functionality within the lab environment. 

Lab 02: Edited to match interface changes and improve functionality within labs.
Lab 03: Edit formatting.
Lab 04: Edits to improve functionality within labs.
Lab 05: Edited to match interface changes and improve functionality within labs.
Lab 06: Edited to match interface changes, removed extra asterisks.
Lab 07: Edited to match interface changes and improve functionality within lab.
Lab 08: Edited to match interface changes and improve functionality within labs.
            Added steps to install Microsoft edge to open the Azure Portal within the created VMs.
            Changed Internet Explorer references to Microsoft Edge where applicable.

### CODE REVIEW

**Review by TJGitHubUser — COMMENTED** [review]
Lab 2, exercise 5, task 5
Can you check the step? Is that correct? Completed the Azure AD Installation Successfully Completed window.. Is there an extra 'Completed' in this step? It may be correct but I didn't want to go into the lab environment just to check this one small issue. Thanks!

**Comment by berkenbrack** [comment]
Hello, I wanted to confirm the In the  proposed **Completed the Azure AD Installation Successfully Completed**, the completed does not appear  in my confirmation prompt. Please see below: 
image
I do not unfortunately have permission to edit that pull request but wanted to advise.

**Review by TJGitHubUser — CHANGES_REQUESTED** [review]
In Lab 2, Exercise 5, Task 5, Step 7 the markdown should read:

In the **Completed the Azure AD Password Protection Proxy Setup Wizard** window, select **Finish**.

This is the only change required, and once made I can authorize the merge of the pull request.

Thanks,
Tony Jamieson

**Comment by clifford-smith** [comment]
Edited to match interface.
1. In the **Installation Successfully Completed** window, select **Close**.
1. In the **Completed the Azure AD Password Protection Proxy Setup Wizard** window, select **Finish**.

**Comment by clifford-smith** [comment]
Hello,

I have made the requested edits.

Cheers

Clifford Smith

**Review by TJGitHubUser — COMMENTED** [review]
Great, thank you for the update. I will approve the merge by requesting our PDETS team to merge this pull request.
Regards,
Tony Jamieson

**Pull request merged**
